// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SteamStoreDbContext))]
    partial class SteamStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FPS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Survival"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Open-world action RPG.",
                            ImageUrl = "https://example.com/images/elden-ring.jpg",
                            Price = 59.99m,
                            Rating = 4.7999999999999998,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Space RPG adventure.",
                            ImageUrl = "https://example.com/images/starfield.jpg",
                            Price = 49.99m,
                            Rating = 4.0999999999999996,
                            Title = "Starfield"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Dark fantasy hack-and-slash RPG.",
                            ImageUrl = "https://example.com/images/diablo4.jpg",
                            Price = 54.99m,
                            Rating = 4.2999999999999998,
                            Title = "Diablo IV"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Fast-paced demon-slaying FPS.",
                            ImageUrl = "https://example.com/images/doom-eternal.jpg",
                            Price = 29.99m,
                            Rating = 4.7000000000000002,
                            Title = "DOOM Eternal"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Competitive tactical FPS.",
                            ImageUrl = "https://example.com/images/cs2.jpg",
                            Price = 0.00m,
                            Rating = 4.5,
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Sci-fi first-person shooter.",
                            ImageUrl = "https://example.com/images/halo-infinite.jpg",
                            Price = 39.99m,
                            Rating = 4.0,
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Turn-based grand strategy game.",
                            ImageUrl = "https://example.com/images/civ6.jpg",
                            Price = 24.99m,
                            Rating = 4.5999999999999996,
                            Title = "Civilization VI"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Epic fantasy strategy battles.",
                            ImageUrl = "https://example.com/images/warhammer3.jpg",
                            Price = 59.99m,
                            Rating = 4.2000000000000002,
                            Title = "Total War: Warhammer III"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Classic real-time strategy modernized.",
                            ImageUrl = "https://example.com/images/aoe4.jpg",
                            Price = 39.99m,
                            Rating = 4.4000000000000004,
                            Title = "Age of Empires IV"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Rogue-like dungeon crawler.",
                            ImageUrl = "https://example.com/images/hades.jpg",
                            Price = 19.99m,
                            Rating = 4.9000000000000004,
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Relaxing farming and life sim.",
                            ImageUrl = "https://example.com/images/stardew-valley.jpg",
                            Price = 14.99m,
                            Rating = 4.7999999999999998,
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Precision platforming indie hit.",
                            ImageUrl = "https://example.com/images/celeste.jpg",
                            Price = 9.99m,
                            Rating = 4.7000000000000002,
                            Title = "Celeste"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Viking survival sandbox.",
                            ImageUrl = "https://example.com/images/valheim.jpg",
                            Price = 19.99m,
                            Rating = 4.5999999999999996,
                            Title = "Valheim"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Underwater survival exploration.",
                            ImageUrl = "https://example.com/images/subnautica.jpg",
                            Price = 24.99m,
                            Rating = 4.7999999999999998,
                            Title = "Subnautica"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Open-world survival horror.",
                            ImageUrl = "https://example.com/images/the-forest.jpg",
                            Price = 17.99m,
                            Rating = 4.2999999999999998,
                            Title = "The Forest"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OwnedGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("OwnedGames", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "demo-user"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.OwnedGame", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("OwnedGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("OwnedGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.Navigation("OwnedGames");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("OwnedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
