name: Backend CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Docker Version
        run: docker --version

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build -f API/Dockerfile -t ghcr.io/munvik/steamdemobackend:latest .

      - name: Push to GHCR
        run: docker push ghcr.io/munvik/steamdemobackend:latest

      - name: Docker Images view
        run: docker images
